In [19]:
import cv2
import numpy as np

In [20]:
image=cv2.imread('C:\\Users\\wenyan\\Pictures\\dics.jpg',0)
#0 灰度   1 彩色
print(image)  #打印矩阵

[[34 35 35 ...  8  8  8]
 [35 37 37 ... 10 10 11]
 [34 36 36 ... 10 10 10]
 ...
 [81 87 83 ... 63 64 66]
 [83 90 86 ... 64 64 66]
 [83 91 88 ... 66 66 69]]


In [21]:
#读取
cv2.imshow('image',image)
cv2.waitKey(3000)
#键盘绑定函数，单位毫秒，0表示等待键盘输入
cv2.destroyAllWindows()
#默认值删除所有窗口，第一个参数为要删除的窗口名

In [25]:
#保存
image_grey=cv2.imread('C:\\Users\\wenyan\\Pictures\\dics.jpg',0)
cv2.imshow('image_grey',image_grey)
k=cv2.waitKey(0)
if k==20:   #Esc退出
   cv2.destroyAllWindos()
elif k==ord('s'):
   cv2.imwrite('C:\\Users\\wenyan\\Pictures\\dicsgrey.png',image_grey)
   cv2.destroyAllWindows()
    
    #如果代码和图像在同一个文件夹，直接文件名即可

In [30]:
#开启摄像头
"""
cv2.VideoCapture()
    0,1表示摄像头编号，也可加视频文件路径; 计算机自带的摄像头为0，外部设备为1
cap.read()
   返回两个参数赋给两个值。第一个参数ret的值为True或False，代表有没有读到图片。
   第二个参数是frame，是当前截取一帧的图片。
if cv2.waitKey(1)&0xFF==ord('q'):
   0xFF是十六进制常数，二进制值为11111111。通过使用位和（和）这个常数，它只留下原始的最后8位
   这么做是为了防止bug，因为在某些系统，waitKey()除了编码出ASCII码，还会有别的东西，
   我们只选择最后一个字节的内容
    """

'cv2.VideoCapture()\n  #0,1表示摄像头编号，一般为0；也可加视频文件路径\n#cap.read()返回两个参数赋给两个值。第一个参数ret的值为True或False，\n  #..代表有没有读到图片。第二个参数是frame，是当前截取一帧的图片。\n    **/\n    '

In [28]:
import numpy as np
import cv2

cap=cv2.VideoCapture(0)
while(True):
    #获取一帧帧图像
    ret,frame=cap.read() 
    gray=cv2.cvtColor(frame,cv2.COLOR_RGB2GRAY)
    cv2.imshow('frame',gray)
    if cv2.waitKey(1)&0xFF==ord('q'):
        break
cap.release()
cv2.destroyAllWindows()

In [31]:
#创建VideoWriter对象
'''
out=cv2.VideoWriter('output.avi',fourcc,24.0,(640,480))
    1视频名字，2Fourcc为4字节码，为编码方式  3播放帧率  4大小  5默认True 彩色
frame=cv2.flip(frame,0)
    1 水平翻转   0 垂直翻转  -1 水平垂直翻转
    
 '''

"\nout=cv2.VideoWriter('output.avi',fourcc,24.0,(640,480))\n    #1视频名字，2Fourcc为4字节码，为编码方式  3播放帧率  4大小  5默认True 彩色\n "

In [10]:
import numpy as np
import cv2
cap=cv2.VideoCapture(0)
#fourcc=cv2.cv.FOURCC(*'XVID') opencv2版本代码
fourcc = cv2.VideoWriter_fourcc(*'XVID') 
out=cv2.VideoWriter('output.avi',fourcc,24.0,(320,240))
i=0
while(cap.isOpened()&(i<50)):   #摄像头开启
    ret,frame=cap.read()
    if ret==True:
        out.write(frame)
        gray = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY) 
        cv2.imshow('frame',gray)
        if cv2.waitKey(1)&0xFF==ord('s'):
            cv2.imwrite('D:/frame00/%d.jpg'%i,gray)
            i += 1
        if cv2.waitKey(1)&0xFF==ord('q'):
            break
    else: 
        break
cap.release()
#out.release()
cv2.destroyAllWindows()
            